package com.codeminders.labs.timeextractor.constants;

public enum Type {
	DATE, TIME, TIMEDATE, TIMEINTERVAL, DATEINTERVAL, TIME_DATE_INTERVAl, DATE_TIME_INTERVAL, DATEINTERVALTIMEINTERVAL, DURATION, FREQUENCY
}
