package com.codeminders.labs.timeextractor.constants;

public enum Type {
    DATE, TIME, TIMEDATE, TIME_INTERVAL, DATE_INTERVAL, TIME_DATE_INTERVAl, DATE_TIME_INTERVAL, DATE_INTERVAL_TIME_INTERVAL, DURATION, FREQUENCY, SET
}
