package com.codeminders.labs.timeextractor.temporal.entities;

public enum Type {
    YEAR, MONTH, DAY_OF_WEEK, DATE, RELATIVE_DATE, TIME, TIME_INTERVAL_INDIRECT, DATE_TIME_INTERVAL_INDIRECT, TIMEZONE, EVERY, TIME_DATE, TIME_INTERVAL, DATE_INTERVAL, TIME_DATE_INTERVAl, DATE_TIME_INTERVAL, DATE_INTERVAL_TIME_INTERVAL, DURATION, DURATION_INTERVAL, FREQUENCY, SET, RELATIVE_TODAY, DAY_OF_WEEK_AND_TIME, DAY_OF_WEEK_WEEK_OF_MONTH;
}
